/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import tienda.ManejoEmpleado;
import tienda.ManejoProducto;
import tienda.ManejoBono;

/**
 *
 * @author LENOVO
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    

    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image setValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/shop_40505.png"));
        return setValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonListCodes = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonState = new javax.swing.JButton();
        jButtonGet = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonSetPro = new javax.swing.JButton();
        jButtonAddCode = new javax.swing.JButton();
        jButtonAddPro = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSalir.setText("Regresar");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 110, 30));

        jButtonListCodes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonListCodes.setText("Listar Bonos");
        jButtonListCodes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListCodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListCodesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListCodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 200, -1));

        jButtonAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAdd.setText("Agregar Empleado");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, -1));

        jButtonState.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonState.setText("Estado Empleado");
        jButtonState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonState, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, -1));

        jButtonGet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonGet.setText("Consultar Empleado");
        jButtonGet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 200, -1));

        jButtonList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonList.setText("Listar Empleados");
        jButtonList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, -1));

        jButtonSetPro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSetPro.setText("Editar Producto");
        jButtonSetPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSetPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetProActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSetPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 200, -1));

        jButtonAddCode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddCode.setText("Crear Bono");
        jButtonAddCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 200, -1));

        jButtonAddPro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAddPro.setText("Agregar Producto");
        jButtonAddPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondotoldo.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
        Tienda in = new Tienda();
        in.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProActionPerformed
        String codigo, nombre, precio;
        ManejoProducto w= new ManejoProducto();
        codigo = JOptionPane.showInputDialog(null,"Ingrese el codigo del producto", "Solicitando datos",
                JOptionPane.INFORMATION_MESSAGE);
       
            nombre = JOptionPane.showInputDialog(null,"Ingrese el nombre del producto", "Solicitando datos",
                    JOptionPane.INFORMATION_MESSAGE);
            precio = JOptionPane.showInputDialog(null, "Ingrese el precio del producto", "Solicitando datos",
                    JOptionPane.INFORMATION_MESSAGE);
            w.AgregarProducto(codigo, nombre, precio); 
           
    }//GEN-LAST:event_jButtonAddProActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String codigo, nombre, apellidos, identificacion;
        String celular;
        int numeroVentas = 0;
        Boolean activo = true;
        ManejoEmpleado e = new ManejoEmpleado();
    
        identificacion = JOptionPane.showInputDialog(null, "Introduzca el id",
                "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
  
        
       
            codigo = JOptionPane.showInputDialog(null, "Introduzca la contraseña",
                    "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
            nombre = JOptionPane.showInputDialog(null, "Introduzca el nombre",
                    "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
            apellidos = JOptionPane.showInputDialog(null, "Introduzca los apellidos",
                    "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
            celular =JOptionPane.showInputDialog(null, "Introduzca el numero de celular",
                    "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
             e.AgregarEmpleado(codigo, identificacion , nombre, apellidos, celular, numeroVentas, activo); 
           
           
         
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStateActionPerformed
        ManejoEmpleado w = new ManejoEmpleado();
        String id= JOptionPane.showInputDialog(null, "Introduzca el id",
                "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
          w.Estadoempleado(id);
                
       
    }//GEN-LAST:event_jButtonStateActionPerformed

    private void jButtonGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetActionPerformed
        String identificacion;
        ManejoEmpleado b= new ManejoEmpleado ();
        identificacion = JOptionPane.showInputDialog(null, "Introduzca el id",
                "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
        b.ConsultarEmpleado(identificacion);
     
        
    }//GEN-LAST:event_jButtonGetActionPerformed

    private void jButtonSetProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetProActionPerformed
        String codigo, precio;
        ManejoProducto w= new ManejoProducto ();
        codigo = JOptionPane.showInputDialog(rootPane, "Ingrese el codigo del producto", "Solicitando datos",
                JOptionPane.INFORMATION_MESSAGE);
        if (w.ConsultarProductoExistente(codigo)== true ){
        precio = JOptionPane.showInputDialog(rootPane, "Ingrese el nuevo precio", "Solicitando datos",
                    JOptionPane.INFORMATION_MESSAGE);
       
        w.EditarProducto(codigo, precio);
        }
        
        else 
        {
         JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de un producto existente",
                    "El producto no existe", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSetProActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
      ManejoEmpleado w= new ManejoEmpleado();
       w.ListarEmpleados();
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonAddCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCodeActionPerformed
        String codigo, descuento;
        ManejoBono w= new ManejoBono();
        
        codigo = JOptionPane.showInputDialog(rootPane, "Ingrese el codigo para el bono",
                "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
        if ( w.ConsultarBonoExistente (codigo) == false ) {
            descuento = JOptionPane.showInputDialog(rootPane, "Ingrese el porcentaje descuento para el bono",
                    "Solicitando datos", JOptionPane.INFORMATION_MESSAGE);
            w.CrearBono (codigo, descuento);
        } 
        
      else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de un bono nuevo", 
                    "El bono ya existe", JOptionPane.INFORMATION_MESSAGE);
        }
         
    }//GEN-LAST:event_jButtonAddCodeActionPerformed

    private void jButtonListCodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListCodesActionPerformed
       ManejoBono w= new ManejoBono();
       w.ListarBonos();
    }//GEN-LAST:event_jButtonListCodesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddCode;
    private javax.swing.JButton jButtonAddPro;
    private javax.swing.JButton jButtonGet;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonListCodes;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSetPro;
    private javax.swing.JButton jButtonState;
    private javax.swing.JLabel jLabelfondo;
    // End of variables declaration//GEN-END:variables
}
