/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tienda.Administrador;

/**
 *
 * @author LENOVO
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    private String barra = File.separator;
    private String location1 = System.getProperty("user.dir") + this.barra + "Registros" + this.barra;
    private String location2 = this.location1 + "Administrador" + this.barra;
    private String location3 = this.location1 + "Empleados" + this.barra;
    private String location4 = this.location1 + "Clientes" + this.barra;
    private String location5 = this.location1 + "Bonos" + this.barra;
    private String location6 = this.location1 + "Productos" + this.barra;

    public Tienda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image setValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/shop_40505.png"));
        return setValue;
    }

    private void crearCarpetas() {
        String location[] = {this.location1, this.location2, this.location3, this.location4, this.location5, this.location6};
        for (int i = 0; i < 6; i++) {
            File crearCarpetas = new File(location[i]);
            if (!crearCarpetas.exists()) {
                crearCarpetas.mkdirs();
            }
        }
        long celular = 3152254018L;
        File admin = new File(this.location2 + "Admin.Registro");
        Administrador adminis = new Administrador("1", 1L, "Hermes Antonio", "Teran Velez", celular);
        if (!admin.exists()) {
            try {
                admin.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
            }
            adminis.guardarDatos(admin);
        } else {
            adminis.modificarDatos(admin, celular);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jTextFieldUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 240, 30));

        jPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 240, 30));

        jButtonLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonLogin.setText("Iniciar Sesion");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSalir.setText("salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 30));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondotoldo.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        crearCarpetas();
        String seleccion[] = {"Administrador", "Empleado"};
        if (jTextFieldUser.getText().equals("") || jPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el usuario y contraseña",
                    "Solicitando datos", JOptionPane.ERROR_MESSAGE);
        } else {
            int opcion = JOptionPane.showOptionDialog(rootPane, "Seleccione una opcion",
                    "Inicio de sesión", 0, JOptionPane.INFORMATION_MESSAGE, null, seleccion, null);
            if (opcion == JOptionPane.YES_OPTION) {
                File administrador = new File(this.location2 + "Admin.Registro");
                RandomAccessFile verificador;
                String lector, substring1, substring2;
                try {
                    verificador = new RandomAccessFile(administrador, "r");
                    lector = verificador.readLine();
                    substring1 = lector.substring(8);
                    lector = verificador.readLine();
                    substring2 = lector.substring(16);
                    verificador.close();
                    if (substring1.equals(this.jPassword.getText()) && substring2.equals(this.jTextFieldUser.getText())) {
                        dispose();
                        Admin ad = new Admin();
                        ad.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor introduzca una contraseña y usuario válidos",
                                "Contraseña incorrecta", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                File empleado = new File(this.location3 + this.jTextFieldUser.getText() + ".Registro");
                if (!empleado.exists()) {
                    JOptionPane.showMessageDialog(null, "Comuniquese con el administrador para que solucione el problema",
                            "El empleado no esta registrado", JOptionPane.WARNING_MESSAGE);
                } else {
                    RandomAccessFile verificador;
                    String lector, substring1, substring2;
                    try {
                        verificador = new RandomAccessFile(empleado, "r");
                        lector = verificador.readLine();
                        substring1 = lector.substring(8);
                        lector = verificador.readLine();
                        lector = verificador.readLine();
                        lector = verificador.readLine();
                        lector = verificador.readLine();
                        lector = verificador.readLine();
                        lector = verificador.readLine();
                        substring2 = lector.substring(8, 12);
                        verificador.close();
                        if (substring1.equals(this.jPassword.getText()) && substring2.equals("true")) {
                            dispose();
                            Compra co = new Compra();
                            co.setVisible(true);
                        } else {
                            if (!substring2.equals("true")) {
                                JOptionPane.showMessageDialog(null, "Comuniquese con el administrador si cree que esto es un error",
                                        "El empleado fue suspendido", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor introduzca una contraseña válida",
                                        "Contraseña incorrecta", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
