/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import tienda.ManejoBono;
import tienda.ManejoCliente;
import tienda.ManejoProducto;

/**
 *
 * @author LENOVO
 */
public class Compra extends javax.swing.JFrame {

    /**
     * Creates new form Compra
     */
   private int total2;
    public Compra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image setValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/shop_40505.png"));
        return setValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldBono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonComprar = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonBuscarBono = new javax.swing.JButton();
        jButtonPuntos = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 300, 30));

        jTextFieldBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 380, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Descuento, Ingrese codigo del cliente o un bono ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 400, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Total Acumulado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 20));

        jButtonComprar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonComprar.setText("Ver total acumulado");
        jButtonComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        jButtonFinalizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSalir.setText("Regresar");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 110, 30));

        jButtonBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 90, -1));

        jButtonBuscarBono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonBuscarBono.setText("Bono");
        jButtonBuscarBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarBonoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 90, -1));

        jButtonPuntos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPuntos.setText("Puntos");
        jButtonPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 90, -1));

        jButtonRegistrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonRegistrar.setText("Registrar Cliente");
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 170, -1));

        jLabelTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 80, 20));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondotoldo.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
        Tienda i = new Tienda();
        i.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
       String codigo = jTextFieldCodigo.getText();
       ManejoProducto w= new ManejoProducto();
       String total;
            total = w.DevolverTotal(codigo).substring(1);
            total2 = total2 + Integer.parseInt(total);
            this.jLabelTotal.setText(Integer.toString(total2));     
    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        String codigo;
       
        ManejoCliente w= new ManejoCliente ();
       
      
        codigo = JOptionPane.showInputDialog(rootPane, "Ingrese el id del cliente para sumar puntos", "Solicitando datos",
                JOptionPane.INFORMATION_MESSAGE);
        int total = Integer.parseInt(this.jLabelTotal.getText().substring(1));
        
          w.AgregarCompra(codigo, total);
         
       
      
        this.jLabelTotal.setText("");
        this.jTextFieldBono.setText("");
        this.jTextFieldCodigo.setText("");
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String codigo = this.jTextFieldCodigo.getText(), nombre, precio;
        ManejoProducto w= new ManejoProducto();
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduzca el codigo", "Error - caja de texto vacia",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            
               w.ConsultarProducto(codigo); 
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBonoActionPerformed

    private void jButtonBuscarBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarBonoActionPerformed
        String codigo = this.jTextFieldBono.getText();
        float var2;
        ManejoBono w= new ManejoBono();
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduzca un bono de descuento", "Error - caja de texto vacia",
                    JOptionPane.ERROR_MESSAGE);
        }
             var2 = Integer.parseInt(this.jLabelTotal.getText().substring(1));
             w.UtilizarBono(codigo, (int) var2);
        
    }//GEN-LAST:event_jButtonBuscarBonoActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        dispose();
        RegistroCliente rc = new RegistroCliente();
        rc.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntosActionPerformed
        
         int var;
        String codigo = this.jTextFieldBono.getText();
        ManejoCliente w= new ManejoCliente();
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese una identificacion",
                    "Error", JOptionPane.ERROR_MESSAGE);           
    }//GEN-LAST:event_jButtonPuntosActionPerformed

             var = Integer.parseInt(this.jLabelTotal.getText().substring(1));
             w.UtilizarPuntos(codigo, var);
   
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarBono;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonPuntos;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JTextField jTextFieldBono;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
